-- PostgreSQL

create table person
(
    id            int generated by default as identity primary key,
    full_name     varchar(100) unique                                        not null,
    year_of_birth int check ( year_of_birth > 1900 and year_of_birth < 2020) not null
);

create table book
(
    id           int generated by default as identity primary key,
    name         varchar(100)                not null unique,
    author       varchar(100)                not null,
    year         int                         not null,
    person_id    int                         references person (id) on DELETE set null null,
    pick_up_time timestamp without time zone null
);